// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fieldbook-directions/Chalk.tsx": () => import("../components/mockups/fieldbook-directions/Chalk.tsx"),
  "./components/mockups/fieldbook-directions/Signal.tsx": () => import("../components/mockups/fieldbook-directions/Signal.tsx"),
  "./components/mockups/fieldbook-directions/Terrain.tsx": () => import("../components/mockups/fieldbook-directions/Terrain.tsx")
};
